<?php
define('CIS_SHORTCODES_API_REV', 1);

/**
 * Implements hook_entity_view().
 */
function cis_shortcodes_entity_view($entity, $type, $view_mode, $langcode) {
  $links = array();
  // only add embed methods on full view with access
  if ($view_mode == 'full' && user_access('view cis shortcode')) {
    // load info so we know what the key id is
    $type_info = entity_get_info($type);
    // build properties array for rendering
    $properties = array(
      'rev' => CIS_SHORTCODES_API_REV,
      'tool' => variable_get('install_profile', ''),
      'item' => $entity->{$type_info['entity keys']['id']},
    );
    // only append type for non-node entities
    if ($type != 'node') {
      $properties['entity_type'] = $type;
    }
    if (module_exists('entity_iframe')) {
      $field['cis_shortcodes']['cis_shortcodes_embed'] = array(
        '#title' => t('Shortcode direct iframe'),
        '#attributes' => array('class' => array('cis_shortcodes_embed')),
        '#value' => _cis_shortcodes_build_code($properties),
        '#type' => 'textfield',
        '#pre_render' => array('_cis_shortcodes_add_js'),
        '#weight' => 1,
      );
    }
    $properties['render'] = 'link';
    $field['cis_shortcodes']['cis_shortcodes_link'] = array(
      '#title' => t('Shortcode direct link'),
      '#attributes' => array('class' => array('cis_shortcodes_embed')),
      '#value' => _cis_shortcodes_build_code($properties),
      '#type' => 'textfield',
      '#weight' => 3,
    );
    // check for unique tag capabilities
    if (isset($entity->field_cis_tag) && isset($entity->field_cis_tag['und'])) {
      unset($properties['render']);
      $properties['item'] = $entity->field_cis_tag['und'][0]['value'];
      $properties['item_type'] = 'tag';
      if (module_exists('entity_iframe')) {
        $field['cis_shortcodes']['cis_shortcodes_tag_iframe'] = array(
          '#title' => t('Shortcode tagged iframe'),
          '#attributes' => array('class' => array('cis_shortcodes_embed')),
          '#value' => _cis_shortcodes_build_code($properties),
          '#type' => 'textfield',
          '#weight' => 2,
        );
      }
      $properties['render'] = 'link';
      $field['cis_shortcodes']['cis_shortcodes_tag_link'] = array(
        '#title' => t('Shortcode tagged link'),
        '#attributes' => array('class' => array('cis_shortcodes_embed')),
        '#value' => _cis_shortcodes_build_code($properties),
        '#type' => 'textfield',
        '#weight' => 4,
      );
    }
    $entity->content['cis_shortcodes'] = array(
      '#markup' => drupal_render($field),
      '#weight' => 100,
    );
  }
}

/**
 * Helper function to ensure js is added with form element.
 */
function _cis_shortcodes_add_js($form) {
  // add js as we know we'll have a code on the page
  drupal_add_js(drupal_get_path('module', 'cis_shortcodes') .'/cis_shortcodes.js');
  return $form;
}

/**
 * Helper to return a built code from properties
 */
function _cis_shortcodes_build_code($properties) {
  $ary = array();
  foreach ($properties as $key => $val) {
    $ary[] = $key . '=' . $val;
  }
  return '[ciscode|' . implode('|', $ary) . ']';
}