<?php
/**
 * Implements hook_cis_service_registry_alter().
 *
 * This is a rare edgecase where you'd want to modify the registry.
 */
function cis_remote_watchdog_cis_service_registry_alter(&$registry) {
  $distro = variable_get('install_profile', FALSE);
  // make sure this distro is valid in our network
  if (isset($registry[$distro])) {
    // divert to a connection address relative to the distro implementing it 
    $registry['remote_watchdog']['service_address'] = $registry[$distro]['service_address'];
    $registry['remote_watchdog']['address'] = $registry[$distro]['address'];
  }
}

/**
 * Impements hook_watchdog().
 */
function cis_remote_watchdog_watchdog(array $log_entry) {
  // build the data array to ship off
  $data = array(
    'uid' => $log_entry['uid'],
    'type' => substr($log_entry['type'], 0, 64),
    'message' => $log_entry['message'],
    'variables' => serialize($log_entry['variables']),
    'severity' => $log_entry['severity'],
    'link' => substr($log_entry['link'], 0, 255),
    'location' => $log_entry['request_uri'],
    'referer' => $log_entry['referer'],
    'hostname' => substr($log_entry['ip'], 0, 128),
    'timestamp' => $log_entry['timestamp'],
  );
  // force message to be sent without waiting for confirmation
  $call_options = array('blocking' => FALSE);
  // push watchdog message to remote_watchdog without waiting for a response
  _cis_connection_object(NULL, 'watchdog', NULL, 'POST', $data, 'remote_watchdog', '', FALSE, '', $call_options);
}